### ISSUE TITLE
North and south latitude problems

### ISSUE THREAD

**Issue by Thornye** [SatAgro/suntime#15]
Unable to get sunrise or sunset on South and North Pole as latitude limited to about 85N and 87S. 
Math issue or bug in the module?

**Comment by deepweather** [comment]
South and North Pole might have no sunset or sunrise

**Comment by Thornye** [comment]
Actually they do. Geographically sunrise March 21 and sunset September 21 on the North pole. Opposite in the south.

**Comment by marvingabler** [comment]
Yes, sunrise and sunset happen a few times a year at the poles. 

You was asking why you are unable to get a sunrise or sunset for a specific day at the poles, and the answer is still because there might be no sunset or sunrise to return. This lib calculates the sunrise/sunset for a specific day.

**Comment by Thornye** [comment]
Still there seems to be a bug or maybe a math issue, and I just wanted the authors to be aware.
