### ISSUE TITLE
cannot import name 'Sun' from partially initialized module 'suntime' (most likely due to a circular import)

### ISSUE THREAD

**Issue by AndKe** [SatAgro/suntime#18]
running the example which starts with:

```
import datetime
from suntime import Sun , SunTimeException

```

...it fails on the second line with 
"ImportError: cannot import name 'Sun' from partially initialized module 'suntime' (most likely due to a circular import) "

**Comment by Litchfield-TWOSE** [comment]
I'm getting the same issue on Python 3.10.  Is there a compatibility issue?

**Comment by AndKe** [comment]
same on 3.9.7 too.

**Comment by Andrei-Iosifescu123** [comment]
If the name of your script is suntime.py, try renaming it to something else. This worked for me on Windows 10 with Python 3.9.5.

**Comment by AndKe** [comment]
yep, that's most likely what caused this - I remember to have seen something similar long time ago.
Thank you.
