### ISSUE TITLE
Bug in day wrap for sunset times

### ISSUE THREAD

**Issue by GuillaumeDec** [SatAgro/suntime#21]
https://github.com/SatAgro/suntime/blob/db63eb830803b52d352f3270ce1938ac2f9a2c69/suntime/suntime.py#L168

This condition can never be true since `force_range` has been called on `hr` before.

This causes a bug in sunset times being before sunrise times. 
Minimam reproducible example:
```
import pandas as pd
from suntime import Sun

sun = Sun(37.7, -122.0) 

assert ( sun.get_sunset_time(date=pd.Timestamp(year=2022, month=11, day=25, hour=22, minute=12, tz="UTC")) > sun.get_sunrise_time(date=pd.Timestamp(year=2022, month=11, day=25, hour=22, minute=12, tz="UTC")) )

```

Great lib otherwise :)

**Comment by kstopa** [comment]
Solved on `1.3.0`
