### ISSUE TITLE
Commit e9b1fa4 has breaking change

### ISSUE THREAD

**Issue by timrprobocom** [SatAgro/suntime#28]
Commit e9b1fa4 changed the source for `get_sunrise_time` and `get_sunset_time` so that the `date` parameter defaults to `datetime.today()`.  Previously, it was the `at_date` parameter and defaulted to `datetime.datetime.now()`.

Unfortunately, those are two different types.  `today()` is a `datettime.date`, and `now()` is a `datetime.datetime`.  The `get_sun_timedelta` method that both of these calls expects a `datetime.datetime`, resulting in a TypeError from `utcoffset`.

**Comment by kstopa** [comment]
Thanks for reporting. Solved in 1.3.2
